name: Publish To NPM
description: Publish koishi plugins to npm
inputs:
  node-version:
    default: '16'
    required: false
    description: Node.js version to use
  token:
    required: true
    description: NPM token
  test:
    default: 'echo ":rocket: Test skipped!"'
    required: false
    description: Test command, if not specified, then not to test
  install-peer:
    default: 'koishi'
    required: false
    description: Peer dependency to install

runs:
  using: composite

  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    - name: Upgrade yarn
      shell: bash
      run: |
        yarn set version stable
        yarn config set nodeLinker node-modules
    - name: Install dependencies
      shell: bash
      env:
       YARN_ENABLE_IMMUTABLE_INSTALLS: "false"
      run: |
        yarn install
        yarn add --dev ${{ inputs.install-peer }}
    - name: Build
      shell: bash
      run: yarn build
    - name: Test
      shell: bash
      run: |
        ${{ inputs.test }} 
    - uses: JS-DevTools/npm-publish@v2
      with:
        token: ${{ inputs.token }}
